require("plugins-setup")
require("core.options")
require("core.keymaps")
require("core.colorscheme")

require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.vim-test")
require("plugins.lsp_config")
require("plugins.gitsigns")
require("plugins.copilot")
